title: Hayley Denyer
logo: /images/Hayley.jpg
# description: "some text." # TODO
blank_title: true
show_downloads: false
# google_analytics: G-123 # TODO
theme: jekyll-theme-minimal
color-scheme: auto
favicon: true

navigation:
- title: about
  path: /
- title: phd
  path: /phd
- title: experience
  path: /experience
- title: publications
  path: /publications
- title: speaking-engagements
  path: /speaking-engagements

social:
- title: twitter
  url: https://twitter.com/hayley_denyer
  icon: fa-brands fa-twitter
- title: linkedin
  url: https://www.linkedin.com/in/hdenyer/
  icon: fa-brands fa-linkedin
